[metadata]
isca = false
ca-cert = "eloo.pem"
ca-key = "eloo.key"

[metadata.expiration]
years = 10
months = 0
days = 0

[subject]
street-address = "address"
postal-code = "00-000"
common-name = "First Root CA Example"
organization = ["Example Company"]
country = ["US"]
province = ["California"]
locality = ["City"]

[dns]
domains = ["example.local"]
ips = ["127.0.0.1"]
